export default {
  port: process.env.PORT,
  frontendUrl: process.env.FRONTEND_URL,
  dbUrl: process.env.DB_URL,
  forgotPasswordTokenSecret: process.env.FORGOT_PASSWORD_TOKEN_SECRET,
  accessTokenPublicKey: process.env.ACCESS_TOKEN_PUBLIC_KEY,
  accessTokenPrivateKey: process.env.ACCESS_TOKEN_PRIVATE_KEY,
  accessTokenExpiry: 1000 * 60 * 60,
  refreshTokenPublicKey: process.env.REFRESH_TOKEN_PUBLIC_KEY,
  refreshTokenPrivateKey: process.env.REFRESH_TOKEN_PRIVATE_KEY,
  refreshTokenExpiry: 1000 * 60 * 60 * 24 * 365,
  cookieMaxAge: 1000 * 60 * 60 * 24 * 365,
  mimeTypes: ["video/mp4"],
  chunkSize: 1000000, //1mb
  googleClientId: process.env.GOOGLE_CLIENT_KEY,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleTokenUri: process.env.GOOGLE_TOKEN_URI as string,
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI as string,
  mailHost: process.env.MAIL_HOST,
  mailPort: process.env.MAIL_PORT,
  mailUser: process.env.MAIL_USER,
  mailPass: process.env.MAIL_PASS,
};
